adminUser: admin
adminPassword: admin
namespace: monitoring
service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
        jsonData:
          # Enforce scraping at 1 second intervals
          timeInterval: 1s
          minInterval: 1s
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/edge
              operator: DoesNotExist 

env:
  # Set the minimum refresh interval for dashboards to 1 second
  GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 1s

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    hands-raised:
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": {
                  "type": "grafana",
                  "uid": "-- Grafana --"
                },
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "fiscalYearStartMonth": 0,
          "graphTooltip": 0,
          "id": 1,
          "links": [],
          "panels": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "PBFA97CFB590B2093"
              },
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "thresholds"
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": 0
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  }
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 0
              },
              "id": 1,
              "options": {
                "colorMode": "value",
                "graphMode": "area",
                "justifyMode": "auto",
                "orientation": "auto",
                "percentChangeColorMode": "standard",
                "reduceOptions": {
                  "calcs": [
                    "lastNotNull"
                  ],
                  "fields": "",
                  "values": false
                },
                "showPercentChange": false,
                "textMode": "auto",
                "wideLayout": true
              },
              "pluginVersion": "12.1.0",
              "targets": [
                {
                  "datasource": {
                    "type": "prometheus",
                    "uid": "PBFA97CFB590B2093",
                    "intervalFactor": "1"
                  },
                  "disableTextWrap": false,
                  "editorMode": "builder",
                  "expr": "twin_hands_handsraised",
                  "fullMetaSearch": false,
                  "includeNullMetadata": true,
                  "interval": "1s",
                  "legendFormat": "__auto",
                  "range": true,
                  "refId": "A",
                  "useBackend": false
                }
              ],
              "title": "Hands raised",
              "type": "stat"
            }
          ],
          "preload": false,
          "refresh": "1s",
          "schemaVersion": 41,
          "tags": [],
          "templating": {
            "list": []
          },
          "time": {
            "from": "now-5m",
            "to": "now"
          },
          "timepicker": {
            "refresh_intervals": [
              "1s",
              "5s",
              "10s",
              "30s",
              "1m",
              "5m",
              "15m",
              "30m",
              "1h",
              "2h",
              "1d"
            ]
          },
          "timezone": "browser",
          "title": "Hands raised",
          "uid": "4ceff1c9-0c03-4c81-9eda-b354d628b980",
          "version": 1
        }
