apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: beta1-device
  namespace: default
spec:
  deviceModelRef:
    name: temperature-model
  nodeName: kubeedge-device
  properties:
    - name: temperature
      collectCycle: 5000
      reportCycle: 5000
      reportToCloud: true
      desired:
        value: "30"
      # pushMethod:
      #   mqtt:
      #     address: tcp://127.0.0.1:1883
      #     topic: temperature/update/json
      #     qos: 0
      #     retained: false
      visitors:
        protocolName: mqtt
        configData:
          clientID: temperature_client
          topic: sensor/beta1-device/getsinglevalue/json
          qos: 1
          retain: false
          username: ""
          password: ""
          cleanSession: true
          keepAlive: 60
  protocol:
    protocolName: mqtt
    configData:
      clientID: "beta1-device-client"
      brokerURL: "tcp://127.0.0.1:1883"
      topic: "sensor/beta1-device/deviceinfo/json"
      message: '{"temperature": "30", "status": "online"}'
      username: ""
      password: ""
      connectionTTL: 30000000000